Python 2.7 AMD CPU:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - export LOOPY_NO_CACHE=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - amd-cl-cpu
  except:
  - tags
Python 2.6 POCL:
  script:
  - export PY_EXE=python2.6
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - export LOOPY_NO_CACHE=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - pocl
  except:
  - tags
Python 3.5 AMD CPU:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - export NO_DOCTESTS=1
  - export LOOPY_NO_CACHE=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - amd-cl-cpu
  except:
  - tags
Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - export LOOPY_NO_CACHE=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  except:
  - tags
Python 2.7 with legacy PyOpenCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - export REQUIREMENTS_TXT="requirements-old-pyopencl.txt"
  - export LOOPY_NO_CACHE=1
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  except:
  - tags
# PyPy AMD CPU:
#   script:
#   - export PY_EXE=pypy
#   - export PYOPENCL_TEST="amd:pu"
#   - export EXTRA_INSTALL="numpy mako"
#   - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
#   - ". ./build-and-test-py-project.sh"
#   tags:
#   - pypy
#   - amd-cl-cpu
#   except:
#   - tags

CentOS binary:
  script:
  - (cd build-helpers; ./make-linux-build-docker.sh --nodate)
  - (cd ./build-helpers; ./loopy-centos6 ../examples/fortran/sparse.floopy)
  artifacts:
    expire_in: 4 weeks
    paths:
    - build-helpers/loopy-centos6
  tags:
  - docker
  only:
  - master

Documentation:
  script:
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh loopy test"
  tags:
  - python3.5
  except:
  - tags
